language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - node_modules

env:
  - NODE_VERSION="6"

before_install:
  - nvm install $NODE_VERSION
  - node --version
  - npm --version
install:
  - npm install -g serverless
deploy:
  - sls deploy
